spring:
  application:
    name: "inkifyai-doc-generator"

logging:
  level:
    root: INFO
    io.github.jenderenco.inkifyai: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

llm:
  ollama:
    url: http://localhost:11434
    model: llama3.2
    temperature: 0.7

openapi:
  fetcher:
    connect-timeout: 5000
    read-timeout: 10000
    max-retries: 3
    retry-delay: 1000
    validate-url: true
    cache-size: 100
    cache-ttl: 3600000
